import type { ResolvingMetadata } from 'next'

export function createResolvingMetadataFixture(): ResolvingMetadata {
  return Promise.resolve({
    metadataBase: null,
    title: { absolute: 'Loopers Commerce', template: '%s | Loopers Commerce' },
    description: null,
    applicationName: null,
    authors: null,
    generator: null,
    keywords: null,
    referrer: null,
    themeColor: null,
    colorScheme: null,
    viewport: null,
    creator: null,
    publisher: null,
    robots: null,
    alternates: null,
    icons: null,
    openGraph: {
      title: { absolute: 'Loopers Commerce', template: null },
      description: 'root description',
      siteName: 'Loopers Commerce',
      locale: 'ko_KR',
      type: 'website',
      url: 'https://shop.example/',
      images: [
        { url: 'https://shop.example/images/week-07/hero-original.jpg' },
      ],
    },
    manifest: null,
    twitter: null,
    facebook: null,
    pinterest: null,
    verification: null,
    appleWebApp: null,
    formatDetection: null,
    itunes: null,
    abstract: null,
    appLinks: null,
    archives: null,
    assets: null,
    bookmarks: null,
    pagination: { previous: null, next: null },
    category: null,
    classification: null,
    other: null,
  })
}
